include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-fakemesh
PKG_VERSION:=1.0.2
PKG_RELEASE:=1

include $(INCLUDE_DIR)/package.mk

define Package/luci-app-fakemesh
  SECTION:=luci
  CATEGORY:=LuCI
  SUBMENU:=3. Applications
  TITLE:=LuCI support for fakemesh
  PKGARCH:=all
endef

define Package/luci-app-fakemesh/description
LuCI support for fakemesh mesh mode configuration and management.
endef

define Build/Configure
endef

define Build/Compile
endef

define Package/luci-app-fakemesh/install
  # Instala tus archivos aquí
endef

$(eval $(call BuildPackage,luci-app-fakemesh))
