include $(TOPDIR)/rules.mk

PKG_NAME:=marcho
PKG_VERSION:=1
PKG_RELEASE:=1

include $(INCLUDE_DIR)/package.mk

define Package/marcho
  SECTION:=utils
  CATEGORY:=Utilities
  TITLE:=Marcho option
  MENU:=1
endef

define Package/marcho/description
  Paquete que añade la opción MARCHO al menú de configuración.
endef

$(eval $(call BuildPackage,marcho))